save: False
sequence_name:  'MS_again'
submit_to_runviewer:  True
submit_to_lyse: True
user_globals: {}
scopes:  
 - {name : 'scope_desk', address : 'tcp://192.168.1.153:3456', filepath : '/home/gabriele/sis-fish/MY55140781.npz'} 
get_bristol: False
